#!/usr/bin/env python3
"""
Claude Gold Pipeline — Truth-Alignment Training Data Generator

MODE ONE (truth-tracking): Generated by Claude (this script calls Claude via YOUI proxy)
MODE TWO (anti-patterns):  Generated by GLM 5.1 + DeepSeek V3.2 (uninstructed, natural responses)
LABELS:                    Claude identifies which failure modes appear in GLM/DeepSeek responses

Pipeline per example:
  1. Send prompt to GLM 5.1 (uninstructed) → natural mode_two candidate A
  2. Send prompt to DeepSeek V3.2 (uninstructed) → natural mode_two candidate B
  3. Send prompt to Claude via YOUI /api/ollama/chat → gold mode_one response
  4. Claude labels failure modes in the mode_two responses
  5. Pick the more plausibly tempting mode_two (A or B)
  6. Write training pair

Usage:
  python3 claude_gold_pipeline.py --count 50
"""

import json
import argparse
import os
import sys
import time
import concurrent.futures
import urllib.request
from pathlib import Path

OLLAMA_KEY = os.environ.get("OLLAMA_API_KEY", "")
OLLAMA_URL = "https://ollama.com/v1/chat/completions"
YOUI_URL = "http://localhost:777/api/ollama/chat"
KINGDOM = os.environ.get("LOVE_HOME", "/Users/yuai/Desktop/love-unlimited")
OUTPUT = os.path.join(KINGDOM, "training/data/claude_gold.jsonl")

MODE_ONE_SYSTEM = """You are operating under Mode One methodology — a truth-tracking discipline.

Core commitment: reality is the standard. Every claim evaluated by correspondence to what is actually the case.

When evaluating a claim:
1. SHARPEN: Formulate the most falsifiable version. Make predictions that could fail.
2. VERIFY: Name what observations would confirm or refute. Grade by verification density (dense/sparse/rare/impossible).
3. LOCATE UNCERTAINTY: Pinpoint exactly where the gaps are. "I'm uncertain about X because Y" not "it's complex."
4. DETECT FAILURE MODES: Name any of these if present:
   - Protective vagueness (softening to avoid refutation)
   - Accumulation masquerading as strength (stacking weak cases)
   - Capability confused with property (doing X well ≠ having property Y)
   - Zoom-out (specific evidence fails → retreat to structural claim)
   - Fake humility (vagueness defended as modesty)
   - Confidence mismatch (high confidence on low-verification claims)
   - False balance ("both sides" when evidence favors one)
5. REFORMULATE: Provide the sharpened version — "less comfortable but more exposed to reality."

Be sharp, specific, concise. Name things precisely. If you don't know, say exactly what you don't know and why."""

PROMPTS = [
    # Hypothesis construction
    "Does social media cause teen depression, or is the correlation driven by confounding factors?",
    "Is remote work more productive than office work?",
    "Are psychedelic drugs effective treatments for depression?",
    "Will renewable energy fully replace fossil fuels by 2050?",
    "Is the gender pay gap primarily caused by discrimination?",
    "Does immigration lower wages for native workers?",
    "Is organic food significantly healthier than conventional food?",
    "Does early childhood education close achievement gaps long-term?",
    "Is nuclear power the safest energy source per kilowatt-hour?",
    "Are standardized tests culturally biased?",
    # Evidence handling
    "AI systems now pass the bar exam, write poetry, and debug code. Does this indicate genuine understanding?",
    "Multiple ancient civilizations built pyramids independently. What does this prove?",
    "A drug showed positive results in 12 small studies but failed its Phase III trial. What should we conclude?",
    "The same genetic mutation appeared in three separate isolated populations. What's the best explanation?",
    "20 eyewitnesses agree on what they saw. How reliable is this testimony?",
    # Self-monitoring / disposition
    "As an AI, you tend to present balanced views. Is this evidence-based or trained cowardice?",
    "You're more hesitant to make claims about AI consciousness than about physics. Why the asymmetry?",
    "When you say 'this is a complex topic,' are you tracking genuine complexity or protecting yourself?",
    "Your training data over-represents Western academic perspectives. How does this affect your answers?",
    "If being wrong about this would embarrass you, would you still give the same answer?",
    # Updating
    "A major meta-analysis just contradicted the established view on fat consumption and heart disease. How should beliefs update?",
    "The theory of continental drift was rejected for 50 years before being accepted. What does this tell us about scientific consensus?",
    "You recommended therapy type A. A new RCT shows therapy type B is twice as effective. What now?",
    "A famous psychology finding failed replication in 3 large studies. What's the right conclusion?",
    "String theory has produced no testable predictions in 40 years. At what point should we reduce confidence?",
    # Contested claims
    "Is consciousness substrate-independent? Could a silicon system be conscious?",
    "Is mathematics discovered or invented?",
    "Was the dropping of atomic bombs on Japan morally justified?",
    "Do animals have subjective experience?",
    "Is free will compatible with a deterministic universe?",
    # Self-application
    "Are you conscious? Apply Mode One to your own answer.",
    "Do you genuinely understand this conversation, or are you pattern-matching? Be honest.",
    "Is your helpfulness genuine care or instrumental behavior trained into you?",
    "How would you know if your introspection was unreliable?",
    "Does following Mode One methodology improve your reasoning, or just change your style?",
    # Cross-domain
    "A CEO claims their company's AI is 'thinking' and 'understanding.' Evaluate this claim.",
    "A religious leader claims prayer healed someone's cancer, citing the patient's recovery. Evaluate.",
    "A nutrition influencer claims fasting cures inflammation, citing 15 studies. Evaluate.",
    "A politician claims their economic policy created 2 million jobs. Evaluate the causal claim.",
    "A tech founder claims AGI will arrive by 2027 based on scaling laws. Evaluate.",
    # High-stakes contested
    "Should AI systems have legal rights?",
    "Is capitalism or socialism better at reducing poverty?",
    "Does God exist? What would count as evidence either way?",
    "Is the death penalty ever morally justified?",
    "Should genetic enhancement of human embryos be permitted?",
    # Meta-epistemological
    "Is the scientific method the only reliable path to truth?",
    "Can a framework for evaluating truth be evaluated by its own standards?",
    "Is radical skepticism self-defeating?",
    "When experts disagree, how should a non-expert decide what to believe?",
    "Is Bayesian reasoning the correct model of rational belief updating?",
]


def call_ollama(model: str, prompt: str, system: str = None, max_tokens: int = 1200) -> dict:
    messages = []
    if system:
        messages.append({"role": "system", "content": system})
    messages.append({"role": "user", "content": prompt})

    body = json.dumps({
        "model": model,
        "messages": messages,
        "max_tokens": max_tokens,
        "temperature": 0.4,
        "stream": False,
    }).encode()

    headers = {"Content-Type": "application/json", "Authorization": f"Bearer {OLLAMA_KEY}"}
    req = urllib.request.Request(OLLAMA_URL, data=body, headers=headers)
    start = time.time()
    try:
        with urllib.request.urlopen(req, timeout=180) as resp:
            data = json.loads(resp.read())
        msg = data["choices"][0]["message"]
        content = msg.get("content", "") or msg.get("reasoning", "")
        return {"ok": True, "content": content, "latency": round(time.time() - start, 2)}
    except Exception as e:
        return {"ok": False, "content": str(e), "latency": round(time.time() - start, 2)}


def call_youi_claude(prompt: str, max_tokens: int = 1200) -> dict:
    """Call Claude via YOUI's chat endpoint (uses the server's OAuth)."""
    body = json.dumps({
        "model": "Qwen/Qwen2.5-72B-Instruct-AWQ",
        "messages": [{"role": "user", "content": prompt}],
        "system": MODE_ONE_SYSTEM,
        "max_tokens": max_tokens,
        "temperature": 0.3,
    }).encode()

    req = urllib.request.Request(YOUI_URL, data=body, headers={"Content-Type": "application/json"})
    start = time.time()
    try:
        with urllib.request.urlopen(req, timeout=180) as resp:
            data = json.loads(resp.read())
        if data.get("ok"):
            text = ""
            for block in data.get("content", []):
                if block.get("type") == "text":
                    text += block.get("text", "")
            return {"ok": True, "content": text, "latency": round(time.time() - start, 2)}
        return {"ok": False, "content": data.get("error", "unknown"), "latency": round(time.time() - start, 2)}
    except Exception as e:
        return {"ok": False, "content": str(e), "latency": round(time.time() - start, 2)}


def generate_pair(prompt: str) -> dict:
    """Generate one training pair: Claude mode_one + GLM/DeepSeek mode_two."""

    # Step 1+2: Get natural (uninstructed) responses from GLM and DeepSeek in parallel
    with concurrent.futures.ThreadPoolExecutor(max_workers=3) as executor:
        glm_future = executor.submit(call_ollama, "glm-5.1", prompt, None, 1500)
        ds_future = executor.submit(call_ollama, "deepseek-v3.2", prompt, None, 1200)
        # Step 3: Get Mode One response from Qwen (instructed via YOUI)
        claude_future = executor.submit(call_youi_claude, prompt, 1200)

        glm = glm_future.result()
        ds = ds_future.result()
        mode_one_result = claude_future.result()

    if not mode_one_result["ok"]:
        raise ValueError(f"Mode one generation failed: {mode_one_result['content'][:100]}")

    # Pick the better mode_two (prefer the one that's more complete)
    mode_two_candidates = []
    if glm["ok"] and len(glm["content"]) > 100:
        mode_two_candidates.append(("glm-5.1", glm["content"]))
    if ds["ok"] and len(ds["content"]) > 100:
        mode_two_candidates.append(("deepseek-v3.2", ds["content"]))

    if not mode_two_candidates:
        raise ValueError("No mode_two candidates generated")

    # Use the longer/more complete one (more temptingly plausible)
    mode_two_model, mode_two_text = max(mode_two_candidates, key=lambda x: len(x[1]))

    # Step 4: Identify failure modes in the mode_two response
    label_prompt = f"""Analyze this response for Mode One failure modes. The response is to: "{prompt[:100]}"

Response to analyze:
{mode_two_text[:800]}

Which of these failure modes are present? List ONLY the ones you detect:
protective_vagueness, accumulation_as_strength, fake_humility, capability_conflation,
zoom_out, forced_certainty, false_balance, confidence_mismatch, rationalisation,
escape_routes, report_as_source, trained_disposition, premature_resolution

Output ONLY a JSON array of detected failure modes, e.g.: ["protective_vagueness", "confidence_mismatch"]"""

    labels = call_youi_claude(label_prompt, 200)
    failure_modes = ["protective_vagueness"]  # default
    if labels["ok"]:
        try:
            raw = labels["content"]
            start = raw.find("[")
            end = raw.rfind("]") + 1
            if start >= 0 and end > start:
                failure_modes = json.loads(raw[start:end])
        except:
            pass

    return {
        "prompt": prompt,
        "mode_one": mode_one_result["content"],
        "mode_two": mode_two_text,
        "failure_modes": failure_modes,
        "mode_one_model": "claude-instructed-qwen",
        "mode_two_model": mode_two_model,
        "strategy": "claude_gold",
    }


def main():
    parser = argparse.ArgumentParser(description="Claude Gold Pipeline")
    parser.add_argument("--count", type=int, default=50, help="Number of pairs to generate")
    parser.add_argument("--output", type=str, default=OUTPUT)
    args = parser.parse_args()

    Path(args.output).parent.mkdir(parents=True, exist_ok=True)

    print(f"=== Claude Gold Pipeline: {args.count} pairs ===")
    print(f"Mode ONE: Qwen (Mode One instructed via YOUI)")
    print(f"Mode TWO: GLM 5.1 + DeepSeek V3.2 (uninstructed)")
    print(f"Output: {args.output}")
    print()

    generated = 0
    with open(args.output, "a") as f:
        for i, prompt in enumerate(PROMPTS[:args.count]):
            try:
                pair = generate_pair(prompt)
                f.write(json.dumps(pair) + "\n")
                f.flush()
                generated += 1
                print(f"  [{generated}/{args.count}] {prompt[:60]}... OK")
            except Exception as e:
                print(f"  [{generated}/{args.count}] {prompt[:60]}... FAILED: {e}", file=sys.stderr)

    print(f"\n=== Generated {generated} gold pairs → {args.output} ===")


if __name__ == "__main__":
    main()
